# -*- coding: utf-8 -*-
"""Dunn.Talitha-PythonCode-ITT103-S2022.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zZIL28NCLdUwuKMMHaxRqAa6ohTP89kA
"""

Author:'Talitha Dunn'
DateCreated:'30/4/2022'
Course:'ITT103'
Purpose:"This is a python program from the pervious pseudocode."


message= input("welcome to JamEx Limited commission calculated python program. \n Please enter 1 to start the program.")
while True:
 sales=int(input('Enter sales'))
 rate = int(input('Enter rate'))
 Class_sale_person = int(input('EnterClass_sale_person'))
 print("sales ")
 print("rate ")
 print("Class_sale_person ")
 if Class_sale_person == 1:
    if sales <= 1000:
        print(0.06 * sales)
    elif 1000 < sales <= 2000:
        print(0.07 * sales)
    else:
        print(0.1 * sales)
 elif Class_sale_person == 2:
    if sales <= 1000:
        print(0.04 * sales)
    else:
        print(0.06 * sales)
 elif Class_sale_person == 3:
      print(0.045 * sales)
      break
else:
  print('Invaild Class')
end=input('Enter 0 to stop the program.')